#set the following variables to absolute paths
CHARM_DIR = /work/hdd/mzu/rao1/charm/ofi-linux-x86_64-cxi-slurmpmi2cray-smp
UNION_FIND_DIR = /u/rao1/unionfind
PREFIX_LIB_DIR = $(UNION_FIND_DIR)/prefixLib
HTRAM_LIB_DIR = $(UNION_FIND_DIR)/htram

#charmc options
ANCHOR= -DANCHOR_ALGO
#ANCHOR= 
PROFILE= -DPROFILING
#for datatype declaration
UNIONFIND= -DUNIONFIND
CHARMC = $(CHARM_DIR)/bin/charmc $(ANCHOR) $(PROFILE) $(UNIONFIND)
OPTS = -std=c++11 -O3 -g
LD_OPTS =

#options for building union-find library and prefix library
PREFIX_LIBS = -L${PREFIX_LIB_DIR} -lprefix
PREFIX_INC = -I${PREFIX_LIB_DIR}

HTRAM_LIBS = -L${HTRAM_LIB_DIR} -lhtram_group
HTRAM_INC = -I${HTRAM_LIB_DIR}

UNION_FIND_LIBS = -L${UNION_FIND_DIR} -lunionFind ${PREFIX_LIBS}
UNION_FIND_INC = -I${UNION_FIND_DIR} ${PREFIX_INC}
